### ISSUE TITLE
Isssue Reg - node-expat@2.3.18 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by Prabhu9876** [storybookjs/aem#120]
I have been trying to integrate aem and storybook with the commands as mentioned in the documentation. While executing this 
**npm install @storybook/aem --save-dev**  its throwing me an error as  **node-expat@2.3.18 install: `node-gyp rebuild`** .

Im using windows 10 Os, kindly let me know how to proceed further

**Comment by CodeByAlex** [comment]
What version of node are you using?

**Comment by Prabhu9876** [comment]
node version -v12.18.0

**Comment by Prabhu9876** [comment]
Issue resolved by using command npm install -g node-expat from main code section
