### ISSUE TITLE
Port all/more aem core components to Kitchen sink

### ISSUE THREAD

**Issue by tripodsan** [storybookjs/aem#15]
the real AEM core components have a lot of logic in their model classes.
in order to display them properly, they need to be partially ported to JS.

**Comment by CodeByAlex** [comment]
@tripodsan do we still need this issue if we are moving away from the conversion approach?

**Comment by tripodsan** [comment]
well, we should have all of the core components somehow available, since people extend from it.
but maybe their java models are not all needed in js.

**Comment by tripodsan** [comment]
[ ] core/wcm/components/tabs/v1/tabs
[ ] core/wcm/components/page/v1/page
[ ] core/wcm/components/form/options/v1/options
[ ] core/wcm/components/form/options/v2/options
[ ] core/wcm/components/form/hidden/v1/hidden
[ ] core/wcm/components/form/hidden/v2/hidden
[ ] core/wcm/components/form/container/v1/container
[ ] core/wcm/components/form/container/v2/container
[ ] core/wcm/components/form/button/v1/button
[ ] core/wcm/components/form/button/v2/button
[ ] core/wcm/components/form/text/v1/text
[ ] core/wcm/components/form/text/v2/text
[ ] core/wcm/components/sharing/v1/sharing
[ ] core/wcm/components/contentfragment/v1/contentfragment
[ ] core/wcm/components/embed/v1/embed/embeddable/youtube
[ ] core/wcm/components/embed/v1/embed/embeddable
[ ] core/wcm/components/embed/v1/embed
[ ] core/wcm/components/title/v1/title
[ ] core/wcm/components/title/v2/title
[ ] core/wcm/components/accordion/v1/accordion
[ ] core/wcm/components/separator/v1/separator
[ ] core/wcm/components/navigation/v1/navigation
[ ] core/wcm/components/carousel/v1/carousel
[ ] core/wcm/components/image/v1/image
[ ] core/wcm/components/image/v2/image
[ ] core/wcm/components/search/v1/search
[ ] core/wcm/components/container/v1/container
[ ] core/wcm/components/contentfragmentlist/v1/contentfragmentlist
[ ] core/wcm/components/button/v1/button
[ ] core/wcm/components/download/v1/download
[ ] core/wcm/components/teaser/v1/teaser
[ ] core/wcm/components/list/v1/list
[ ] core/wcm/components/languagenavigation/v1/languagenavigation
[ ] core/wcm/components/text/v1/text
[ ] core/wcm/components/text/v2/text
[ ] core/wcm/components/breadcrumb/v1/breadcrumb
[ ] core/wcm/components/breadcrumb/v2/breadcrumb
[ ] core/wcm/components/experiencefragment/v1/experiencefragment

**Comment by CodeByAlex** [comment]
This issue was originally created to include to convert models to js.
