### ISSUE TITLE
Render: the decoration tag logic is not correct

### ISSUE THREAD

**Issue by tripodsan** [storybookjs/aem#23]
in the current code, the `decorationTag` is initialized as an empty object, so the checks are always true...

**Comment by CodeByAlex** [comment]
@jzeltman can you take a look into this?

**Comment by jzeltman** [comment]
@tripodsan @CodeByAlex 
It's meant to be true by default because AEM wraps components by default. It does not output if `decorationTag` is set to `null`.

**Comment by tripodsan** [comment]
> It does not output if `decorationTag` is set to `null`.

ok. got it...so the component definition needs to set `decorationTag: null` in order to suppress the tag.
maybe we can simplify the logic a bit by defining a flag in rendner.ts:
```
const hasDecorationTag = decorationTag !== null;
```
to make the following code more readable...

**Comment by CodeByAlex** [comment]
I like that idea a lot

**Comment by jzeltman** [comment]
@tripodsan  @CodeByAlex 
https://github.com/storybookjs/aem/pull/25/
```
const hasDecorationTag = decorationTag !== null;
```
I've made a PR that incorporates this idea, and also refactors the render method to hopefully be a bit more readable.

**Comment by jzeltman** [comment]
@tripodsan @CodeByAlex Can we close this one now?
