### ISSUE TITLE
Fix typescript errors thrown during prepare script

### ISSUE THREAD

**Issue by CodeByAlex** [storybookjs/aem#46]

**Comment by jzeltman** [comment]
@CodeByAlex 
Was this fixed by [PR](https://github.com/storybookjs/aem/pull/44)?

**Comment by CodeByAlex** [comment]
Yes and no - so the prepare script runs but there are ts errors that need to be fixed. I’ll update the title

**Comment by CodeByAlex** [comment]
@jzeltman is this something you would want to pick up to get us closer to publishing?

**Comment by jpica11** [comment]
I took a look at this an believe it's resolved here: [49](https://github.com/storybookjs/aem/pull/49)
