### ISSUE TITLE
Update compiler for multi-directory output

### ISSUE THREAD

**Issue by jzeltman** [storybookjs/aem#63]
Currently the `tsc` compiler only outputs to the `aem/app/dist` directory. Needs to output to the dist directory in `cli/dist` and `aem/app/dist`

**Comment by CodeByAlex** [comment]
@jzeltman we probably should just have it taker in a single argument that represents an output directory. We can then set those up in each of the library's package json files

**Comment by jzeltman** [comment]
This has been completed with PR #64
