### ISSUE TITLE
Update CLI commands to be more flexible with project folder structure

### ISSUE THREAD

**Issue by jzeltman** [storybookjs/aem#70]
The CLI currently expects a specific folder structure, this should be made more flexible, and follow the configuration more closely, with fewer assumptions.

**Comment by megazear7** [comment]
@jzeltman Most of this was resolved in the following pull request: https://github.com/storybookjs/aem/pull/81

There might still be some assumptions, but every path is listed as an absolute path from the package.json. It currently works with the Adobe Archetype as well as at least two other projects that have different project strucures.

In light of this, should this issue remain open or be closed?

**Comment by jzeltman** [comment]
@megazear7 Sounds like making each path an absolute path resolves this issue. Closing now.
