### ISSUE TITLE
Add resource resolver

### ISSUE THREAD

**Issue by tripodsan** [storybookjs/aem#8]
many components include sub-resources and render them via the resource type (eg `list` component). for the resource include to work correctly, a resource resolver that operates on mock repository content is needed.

also see https://sling.apache.org/documentation/the-sling-engine/resources.html

although we should not implement the entire sling resource API, some core concepts can be copied:
- [Resource](https://github.com/apache/sling-org-apache-sling-api/blob/master/src/main/java/org/apache/sling/api/resource/Resource.java)
- [ResourceResolver](https://github.com/apache/sling-org-apache-sling-api/blob/master/src/main/java/org/apache/sling/api/resource/ResourceResolver.java)
- [ValueMap](https://github.com/apache/sling-org-apache-sling-api/blob/master/src/main/java/org/apache/sling/api/resource/ValueMap.java)

**Comment by CodeByAlex** [comment]
@tripodsan should this be a part of the htl engine or a separate library - sounds useful enough to be used for other purposes

**Comment by tripodsan** [comment]
I don't think it should be part of the htl-engine...for now I would keep it in storybook aem to incubate and the maybe promote to it's own package.

**Comment by jantimon** [comment]
Hey @tripodsan 

we have just implemented a working resource loader and have a running AEM / Storybook system.  

Maybe I can setup a short call to can you some problems we faced e.g. https://github.com/adobe/htlengine/issues/146 and how we solved to get the following example to work in AEM and storybook:

```
<sly data-sly-resource="${'article-overview' @ resourceType='demo/components/demo/article-overview'}" />
```

By now the following directives are running side-by-side in AEM and Storybook (thanks to `@adobe/htlengine`):

- data-sly-use
- data-sly-test
- data-sly-repeat
- data-sly-resource

You can contact me on twitter @jantimon if you like

**Comment by CodeByAlex** [comment]
@tripodsan Does this still need more work?

**Comment by tripodsan** [comment]
let's close it for now.
