### ISSUE TITLE
CLI Error with Chalk Module

### ISSUE THREAD

**Issue by megazear7** [storybookjs/aem#83]
I am getting the following error when running `sba -v` using the `@storybook/aem-cli` version `0.0.8`.

```
$ sba -v
/Users/35267/.nvm/versions/node/v12.16.1/lib/node_modules/@storybook/aem-cli/dist/index.js:50
                chalk.italic(cmd) + " is not a valid command.",

                      ^

TypeError: chalk.italic is not a function
```

**Comment by jzeltman** [comment]
If you're actually running `sba -b`, that's not supported, so it will probably jump to the bottom of the `cli/src/index` file and throw the log there. Looks like we're importing `import * as chalk from 'chalk'` at the top of that file, but I think it should probably just be `import chalk from 'chalk'`

**Comment by megazear7** [comment]
Oopse, I meant to put `sba -v`. I updated the original comment.

**Comment by megazear7** [comment]
And I just realized that `-v` is also not valid, but then remembered that that was actually the point of this issue, the "here are the valid commands" message is not give to the user because it hits an error. This is fixed in pull request https://github.com/storybookjs/aem/pull/84.
