### ISSUE TITLE
'properties' global varaible missing

### ISSUE THREAD

**Issue by tripodsan** [storybookjs/aem#90]
in the sling htl engine, `properties` refers to the properties of the current resource.
this should also be available in storybook.

see: https://sling.apache.org/documentation/bundles/scripting/scripting-htl.html#global-objects

suggest to add all the global properties with meaningful default values:

| name             | sling type                                        | storybook type
|------------------|---------------------------------------------------|--------------|
| `currentNode`    | `javax.jcr.Node`                                  | current content object |
| `currentSession` | `javax.jcr.Session`                               | `NopProxy()` |
| `log`            | `org.slf4j.Logger`                                | `console` |
| `out`            | `java.io.PrintWriter`                             | `() => ()` |
| `properties`     | `org.apache.sling.api.resource.ValueMap`          | current content object |
| `reader`         | `java.io.BufferedReader`                          | `NopProxy()` |
| `request`        | `org.apache.sling.api.SlingHttpServletRequest`    | `NopProxy()` Note: this is quite important and we should provide a good request abstraction |
| `resolver`       | `org.apache.sling.api.resource.ResourceResolver`  | `NopProxy()` |
| `resource`       | `org.apache.sling.api.resource.Resource`          | current content object |
| `response`       | `org.apache.sling.api.SlingHttpServletResponse`   | `NopProxy()` |
| `sling`          | `org.apache.sling.api.scripting.SlingScriptHelper`| `NopProxy()` |

**Comment by madoni** [comment]
@tripodsan I did modify the storybook/aem project to include `properties` object and have been using that locally. Should I create a PR?

**Comment by tripodsan** [comment]
in addition, there are global properties defined by aem:
https://docs.adobe.com/content/help/en/experience-manager-htl/using/htl/global-objects.html

| name             | aem type                                        | storybook type
|------------------|---------------------------------------------------|--------------|
| `inheritedPageProperties` | | `{}` |
| `component` |  com.day.cq.wcm.api.components.Component | _component_ object |
| `componentContext` |  com.day.cq.wcm.api.components.ComponentContext | `NopProxy()` |
| `currentDesign` |  com.day.cq.wcm.api.designer.Design | `NopProxy()`|
| `currentPage` |  com.day.cq.wcm.api.Page | `NopProxy()` |
| `currentStyle` |  com.day.cq.wcm.api.designer.Style | `NopProxy()` |
| `designer` |  com.day.cq.wcm.api.designer.Designer | `NopProxy()` |
| `editContext` |  com.day.cq.wcm.api.components.EditContext | `NopProxy()` |
| `pageManager` |  com.day.cq.wcm.api.PageManager | `NopProxy()` |
| `resourceDesign` |  com.day.cq.wcm.api.designer.Design | `NopProxy()` |
| `resourcePage` |  com.day.cq.wcm.api.Page | `NopProxy()` |
| `slyWcmHelper` |  com.adobe.cq.sightly.WCMScriptHelper | `NopProxy()` |
| `wcmmode` |  com.adobe.cq.sightly.SightlyWCMMode | `{}` |
| `xssAPI` |  com.adobe.granite.xss.XSSAPI | `NopProxy()` |
